[package]
name = "appport-auth-mesh-server"
version = "0.1.0"
edition = "2021"

[dependencies]
appport-auth-mesh-authz = { path = "../authz" }
appport-auth-mesh-boundary = { path = "../boundary" }
appport-auth-mesh-contract = { path = "../contract" }
appport-auth-mesh-discovery = { path = "../discovery" }
appport-auth-mesh-dsl = { path = "../dsl" }
appport-auth-mesh-providers = { path = "../providers" }
appport-auth-mesh-runtime = { path = "../runtime" }
appport-auth-mesh-storage = { path = "../storage" }
appport-auth-mesh-surface = { path = "../surface" }
